import { API_URL } from 'constants';

export const sagaTypes = {
  USER_LIST_REQUEST: 'USER_LIST_REQUEST',
  USER_DETAIL_REQUEST: 'USER_DETAIL_REQUEST',
  DISPLAY_ALERT: 'ALERT_MESSAGE',
  REMOVE_ALERT: 'REMOVE_ALERT',
};

export const actionTypes = {
  DISPLAY_ALERT_MESSAGE: 'DISPLAY_ALERT_MESSAGE',
  REMOVE_ALERT_MESSAGE: 'REMOVE_ALERT_MESSAGE',
  USER_LIST_REQUEST_PROCESSING: 'USER_LIST_REQUEST_PROCESSING',
  USER_LIST_REQUEST_PROCESSED: 'USER_LIST_REQUEST_PROCESSED',
  USER_LIST_REQUEST_PROCESSING_ERROR: 'USER_LIST_REQUEST_PROCESSING_ERROR',
  USER_DETAIL_REQUEST_PROCESSING: 'USER_DETAIL_REQUEST_PROCESSING',
  USER_DETAIL_REQUEST_PROCESSED: 'USER_DETAIL_REQUEST_PROCESSED',
  USER_DETAIL_REQUEST_PROCESSING_ERROR: 'USER_DETAIL_REQUEST_PROCESSING_ERROR',
};

export const apiURLs = {
  userList: `${API_URL}/students`,
  userDetail: `${API_URL}/students`,
};
